### ISSUE TITLE
Update requirements.txt (conda/pip)

### ISSUE THREAD

**Issue by armish** [openvax/mhcflurry-web#1]
To help with testing while this is in the works. Here is what I did to meet all the requirements:

```shell
# Get help from conda for hard-to-install packages
#  and create a new isolated Py3 environment with flask in it
conda create -n mweb python=3 flask
source activate mweb

# Install NN-related ones
conda install -y tensorflow keras theano

# Install ML- and data-related ones
conda install -y numpy scipy pandas scikit-learn

# Install the notorious biopython one
conda install -y biopython

# Now pip-install the rest
pip install mhctools mhcflurry
```
 
which can formally be defined as a conda env file:

```yaml
# run: conda env create --file conda-env.yml
name: mhcweb
channels:
  - bioconda
  - trung
  - conda-forge
dependencies:
  - python=3
  - flask
  - tensorflow
  - keras
  - theano
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - biopython
  - pip:
    - mhctools
    - mhcflurry
```

and be used to create a fresh conda env via:

```shell
conda  env create --file conda-env.yml
source activate mhcweb
```
